# Generated by Django 4.2.3 on 2023-07-30 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rename_image_notification_profile_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='post_id',
            new_name='forward_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='profile_id',
        ),
    ]
