# Generated by Django 4.2.3 on 2023-07-25 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 7, 56, 28, 23277, tzinfo=datetime.timezone.utc)),
        ),
    ]
