# Generated by Django 4.2.4 on 2023-08-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_gender_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('regular-user', 'Regular User'), ('moderator', 'Moderator'), ('admin', 'Admin')], default='regular-user', max_length=25),
        ),
    ]
