# Generated by Django 4.2.4 on 2023-08-09 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('moderator', 'Moderator'), ('admin', 'Admin'), ('regular-user', 'Regular User')], default='regular-user', max_length=25),
        ),
        migrations.AlterField(
            model_name='emailchangecode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 18, 12, 59, 392447, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 18, 12, 59, 392447, tzinfo=datetime.timezone.utc)),
        ),
    ]
