# Generated by Django 4.2.3 on 2023-07-30 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 30, 7, 21, 34, 508633, tzinfo=datetime.timezone.utc)),
        ),
    ]
