# Generated by Django 4.2.1 on 2023-05-20 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_passwordresetcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 20, 11, 17, 17, 654143, tzinfo=datetime.timezone.utc)),
        ),
    ]
