# Generated by Django 4.2.3 on 2023-07-31 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_passwordresetcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 31, 14, 37, 56, 392860, tzinfo=datetime.timezone.utc)),
        ),
    ]
