# Generated by Django 4.2.1 on 2023-06-05 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_customuser_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 5, 8, 43, 33, 794245, tzinfo=datetime.timezone.utc)),
        ),
    ]
