# Generated by Django 4.2.4 on 2023-08-16 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_block_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserStatus',
        ),
    ]
