# Generated by Django 4.2.1 on 2023-05-22 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_topic_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicfollow',
            name='profile',
        ),
        migrations.AddField(
            model_name='topicfollow',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
