# Generated by Django 4.2.1 on 2023-05-22 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_topicfollow_profile_topicfollow_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopicFollow',
        ),
    ]
