# Generated by Django 4.2.1 on 2023-05-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_topicfollow'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='topicfollow',
            constraint=models.UniqueConstraint(fields=('user', 'topic'), name='unique_user_topic'),
        ),
    ]
