# Generated by Django 4.2.1 on 2023-05-27 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_topic_image_path_topic_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Block',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='TopicFollow',
        ),
        migrations.DeleteModel(
            name='UserStatus',
        ),
    ]
