# Generated by Django 4.2.1 on 2023-06-02 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_follow_followed_alter_follow_follower_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='following_count',
        ),
    ]
