# Generated by Django 4.2.1 on 2023-06-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_profile_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(blank=True, default='cover_images/default.jpg', null=True, upload_to='cover_images/'),
        ),
    ]
