# Generated by Django 4.2.3 on 2023-08-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reaction',
            field=models.IntegerField(blank=True, choices=[(3, 'haha'), (5, 'sad'), (2, 'love'), (4, 'wow'), (1, 'like'), (6, 'angry')], null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('voice_record', 'Voice Record')], max_length=20),
        ),
    ]
