# Generated by Django 4.2.3 on 2023-07-18 21:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_remove_message_author_remove_message_chat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('reaction', models.IntegerField(blank=True, choices=[(6, 'angry'), (3, 'haha'), (5, 'sad'), (4, 'wow'), (1, 'like'), (2, 'love')], null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat_images/')),
                ('voice_record', models.FileField(blank=True, null=True, upload_to='voice_records/', validators=[django.core.validators.FileExtensionValidator(['wav', 'mp3'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chat')),
            ],
        ),
    ]
