# Generated by Django 4.2.3 on 2023-08-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_reaction_alter_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reaction',
            field=models.IntegerField(blank=True, choices=[(6, 'angry'), (5, 'sad'), (2, 'love'), (1, 'like'), (3, 'haha'), (4, 'wow')], null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('voice_record', 'Voice Record'), ('image', 'Image'), ('text', 'Text')], max_length=20),
        ),
    ]
