# Generated by Django 4.2.4 on 2023-08-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_reaction_alter_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reaction',
            field=models.IntegerField(blank=True, choices=[(6, 'angry'), (3, 'haha'), (2, 'love'), (4, 'wow'), (1, 'like'), (5, 'sad')], null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('voice_record', 'Voice Record'), ('text', 'Text'), ('image', 'Image')], max_length=20),
        ),
    ]
