# Generated by Django 4.2.3 on 2023-08-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_reaction_alter_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reaction',
            field=models.IntegerField(blank=True, choices=[(5, 'sad'), (6, 'angry'), (1, 'like'), (4, 'wow'), (3, 'haha'), (2, 'love')], null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('voice_record', 'Voice Record')], max_length=20),
        ),
    ]
