# Generated by Django 4.2.4 on 2023-08-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_message_reaction_alter_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reaction',
            field=models.IntegerField(blank=True, choices=[(1, 'like'), (6, 'angry'), (3, 'haha'), (4, 'wow'), (5, 'sad'), (2, 'love')], null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('voice_record', 'Voice Record'), ('image', 'Image'), ('text', 'Text')], max_length=20),
        ),
    ]
