# Generated by Django 4.2.4 on 2023-08-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_message_reaction_alter_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reaction',
            field=models.IntegerField(blank=True, choices=[(1, 'like'), (4, 'wow'), (2, 'love'), (3, 'haha'), (6, 'angry'), (5, 'sad')], null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('voice_record', 'Voice Record'), ('text', 'Text')], max_length=20),
        ),
    ]
