# Generated by Django 4.2.3 on 2023-07-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_message_reaction_alter_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reaction',
            field=models.IntegerField(blank=True, choices=[(4, 'wow'), (5, 'sad'), (3, 'haha'), (1, 'like'), (2, 'love'), (6, 'angry')], null=True),
        ),
    ]
