# Generated by Django 4.2.3 on 2023-07-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_message_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reaction',
            field=models.IntegerField(blank=True, choices=[(6, 'angry'), (5, 'sad'), (4, 'wow'), (1, 'like'), (2, 'love'), (3, 'haha')], null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('text', 'Text'), ('voice_record', 'Voice Record')], max_length=20),
        ),
    ]
