# Generated by Django 4.2.3 on 2023-07-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_message_reaction_alter_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reaction',
            field=models.IntegerField(blank=True, choices=[(6, 'angry'), (1, 'like'), (2, 'love'), (4, 'wow'), (3, 'haha'), (5, 'sad')], null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('voice_record', 'Voice Record'), ('text', 'Text')], max_length=20),
        ),
    ]
