# Generated by Django 4.2.3 on 2023-07-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_chat_updated_at_alter_message_reaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reaction',
            field=models.IntegerField(blank=True, choices=[(3, 'haha'), (4, 'wow'), (2, 'love'), (5, 'sad'), (1, 'like'), (6, 'angry')], null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('voice_record', 'Voice Record'), ('image', 'Image')], max_length=20),
        ),
    ]
