<<<<<<< HEAD
# Generated by Django 4.2.3 on 2023-07-30 09:03
=======
# Generated by Django 4.2.3 on 2023-07-30 06:51
>>>>>>> 1b5ef8d192d325113bc1c1cd7734e0c6cc6fdd53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_message_reaction_alter_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reaction',
<<<<<<< HEAD
            field=models.IntegerField(blank=True, choices=[(3, 'haha'), (4, 'wow'), (5, 'sad'), (1, 'like'), (6, 'angry'), (2, 'love')], null=True),
=======
            field=models.IntegerField(blank=True, choices=[(3, 'haha'), (1, 'like'), (6, 'angry'), (2, 'love'), (5, 'sad'), (4, 'wow')], null=True),
>>>>>>> 1b5ef8d192d325113bc1c1cd7734e0c6cc6fdd53
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
<<<<<<< HEAD
            field=models.CharField(choices=[('image', 'Image'), ('voice_record', 'Voice Record'), ('text', 'Text')], max_length=20),
=======
            field=models.CharField(choices=[('voice_record', 'Voice Record'), ('text', 'Text'), ('image', 'Image')], max_length=20),
>>>>>>> 1b5ef8d192d325113bc1c1cd7734e0c6cc6fdd53
        ),
    ]
