# Generated by Django 4.2.3 on 2023-07-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_message_reaction_alter_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reaction',
            field=models.IntegerField(blank=True, choices=[(3, 'haha'), (4, 'wow'), (5, 'sad'), (1, 'like'), (6, 'angry'), (2, 'love')], null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('voice_record', 'Voice Record'), ('text', 'Text')], max_length=20),
        ),
    ]
