# Generated by Django 4.2.3 on 2023-07-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_alter_message_reaction_alter_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reaction',
            field=models.IntegerField(blank=True, choices=[(4, 'wow'), (6, 'angry'), (3, 'haha'), (2, 'love'), (5, 'sad'), (1, 'like')], null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('voice_record', 'Voice Record')], max_length=20),
        ),
    ]
