# Generated by Django 4.2.3 on 2023-07-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_alter_message_reaction_alter_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reaction',
            field=models.IntegerField(blank=True, choices=[(5, 'sad'), (3, 'haha'), (6, 'angry'), (4, 'wow'), (1, 'like'), (2, 'love')], null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('text', 'Text'), ('voice_record', 'Voice Record')], max_length=20),
        ),
    ]
