# Generated by Django 4.2.4 on 2023-08-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('harassment', 'Harassment'), ('inappropriate-content', 'Inappropriate content'), ('spam', 'Spam')], max_length=25),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('resolved', 'Resolved'), ('redirected', 'Redirected'), ('pending', 'Pending')], default='pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('chat', 'Chat'), ('post', 'Post'), ('user', 'User')], max_length=25),
        ),
    ]
