# Generated by Django 4.2.4 on 2023-08-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('inappropriate-content', 'Inappropriate content')], max_length=25),
        ),
    ]
