# Generated by Django 4.2.4 on 2023-08-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_report_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('spam', 'Spam'), ('inappropriate-content', 'Inappropriate content'), ('harassment', 'Harassment')], max_length=25),
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('post', 'Post'), ('chat', 'Chat'), ('user', 'User')], max_length=25),
        ),
    ]
