# Generated by Django 4.2.4 on 2023-08-08 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_reaction_alter_message_type'),
        ('report', '0002_alter_report_category_alter_report_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reported_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_chat', to='chat.chat'),
        ),
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('harassment', 'Harassment'), ('spam', 'Spam'), ('inappropriate-content', 'Inappropriate content')], max_length=25),
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('chat', 'Chat'), ('user', 'User'), ('post', 'Post')], max_length=25),
        ),
    ]
