# Generated by Django 4.2.4 on 2023-08-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_report_reported_chat_alter_report_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('redirected', 'Redirected'), ('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', max_length=25),
        ),
        migrations.DeleteModel(
            name='Warn',
        ),
    ]
