# Generated by Django 4.2.4 on 2023-08-08 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0004_alter_report_status_delete_warn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('inappropriate-content', 'Inappropriate content')], max_length=25),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('redirected', 'Redirected')], default='pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('post', 'Post'), ('user', 'User'), ('chat', 'Chat')], max_length=25),
        ),
        migrations.CreateModel(
            name='Warn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.report')),
                ('warned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warned_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
