# Generated by Django 4.2.4 on 2023-08-09 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_message_reaction_alter_message_type'),
        ('posts', '0001_initial'),
        ('report', '0005_alter_report_category_alter_report_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reported_post_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('inappropriate-content', 'Inappropriate content'), ('harassment', 'Harassment'), ('spam', 'Spam')], max_length=25),
        ),
        migrations.AlterField(
            model_name='report',
            name='reported_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reported_chat', to='chat.chat'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reported_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reported_post', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('resolved', 'Resolved'), ('pending', 'Pending'), ('redirected', 'Redirected')], default='pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('chat', 'Chat'), ('post', 'Post'), ('user', 'User')], max_length=25),
        ),
    ]
