# Generated by Django 4.2.4 on 2023-08-09 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('report', '0006_report_reported_post_data_alter_report_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='reported_post_data',
        ),
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('harassment', 'Harassment'), ('inappropriate-content', 'Inappropriate content'), ('spam', 'Spam')], max_length=25),
        ),
        migrations.AlterField(
            model_name='report',
            name='reported_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_post', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('resolved', 'Resolved'), ('redirected', 'Redirected'), ('pending', 'Pending')], default='pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('post', 'Post'), ('user', 'User'), ('chat', 'Chat')], max_length=25),
        ),
    ]
