# Generated by Django 4.2.3 on 2023-07-25 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes_count',
        ),
    ]
