# Generated by Django 4.2.3 on 2023-07-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_comments_count_remove_post_likes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
