# Generated by Django 4.2.3 on 2023-07-25 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_point_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='profile',
        ),
    ]
