# Generated by Django 4.2.3 on 2023-07-31 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('posts', '0005_remove_point_profile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('post', 'profile')},
        ),
    ]
